### ISSUE TITLE
the performance of trained model on 3DMatch

### ISSUE THREAD

**Issue by royeLin** [XuyangBai/D3Feat.pytorch#11]
Hi,
I just testing the performance on 3DMatch with trained model.
The performance is in log as follows.

sun3d-hotel_umd-maryland_hotel3: Recall=0.00%, inlier ratio=0.00%, inlier num=0.00
sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika: Recall=0.00%, inlier ratio=0.06%, inlier num=0.03
sun3d-hotel_umd-maryland_hotel1: Recall=0.00%, inlier ratio=0.02%, inlier num=0.01
sun3d-home_at-home_at_scan1_2013_jan_1: Recall=0.64%, inlier ratio=0.11%, inlier num=0.07
sun3d-hotel_uc-scan3: Recall=0.44%, inlier ratio=0.08%, inlier num=0.06
sun3d-home_md-home_md_scan9_2012_sep_30: Recall=0.00%, inlier ratio=0.02%, inlier num=0.01
sun3d-mit_76_studyroom-76-1studyroom2: Recall=0.34%, inlier ratio=0.10%, inlier num=0.07
7-scenes-redkitchen: Recall=92.29%, inlier ratio=25.22%, inlier num=15.86
****************************************
[0.0, 0.0, 0.0, 0.6410256410256411, 0.4424778761061947, 0.0, 0.3424657534246575, 92.29249011857708]
All 8 scene, average recall: 11.71%
All 8 scene, average num inliers: 2.01
All 8 scene, average num inliers ratio: 3.20%

Is it normal?
Best regards, Yu-Kai Lin

**Comment by XuyangBai** [comment]
It is not normal. It seems only the `7-scenes` has normal results, did you only train your model on a subset?

**Comment by zouyajing** [comment]
do you still have the pre-trained model of d3feat pytorch? seems the link in this repo has expired. much appreciated if u could share the model with me. thx.
