### ISSUE TITLE
Kernel weights rescaling

### ISSUE THREAD

**Issue by darshanakgr** [XuyangBai/D3Feat.pytorch#12]
Hi
I have trained the model with a down-sampling rate of 0.3. But I need to test the model for different down-sampling rates. I am aware of the rescaling kernel weights technique that has been used in TensorFlow implementation. Have you implemented the same technique in this implementation too? 
Thank you

**Comment by XuyangBai** [comment]
Hi Thanks for your interest. You can use the following code to rescale the kernel points
```
    weights = torch.load(f'snapshot/{args.chosen_snapshot}/models/model_best_acc.pth', map_location='cpu')['state_dict']
    for key, value in weights.items():
        if 'kernel_points' in key:
            weights[key] = value * config.first_subsampling_dl / 0.03
    model.load_state_dict(weights)
```

**Comment by darshanakgr** [comment]
Thank you for providing the code
