### ISSUE TITLE
Demo code for D3Feat

### ISSUE THREAD

**Issue by fabiopoiesi** [XuyangBai/D3Feat.pytorch#13]
Hi,

Do you guys have a simple demo code, that given two point clouds, D3Feat computes the features and then these features are used to register the two point clouds with RANSAC?

Thanks

**Comment by qsisi** [comment]
I think for methods based on KPConv, it is not easy to directly apply it to single point cloud. As far as I know, KPConv needs to calibrate the appropriate **neighborhood_limits** first, so it's better to rewrite the **Dataset** and organize it to keep in same with that in D3Feat. 

So all we need to do it's to rewrite the **Dataset class** for specific pointclouds and change the parameter **first_subsampling_dl** to be similar to the **voxel_size** of your own pointcloud data.

**Comment by fabiopoiesi** [comment]
I was actually thinking something simpler than that.
Something like the do in [FCGF](https://github.com/chrischoy/FCGF/blob/master/demo.py).
Given a pcd as input, get the features as output.

**Comment by XuyangBai** [comment]
Hi, sorry for the late reply. I did provide a demo script for the [TensorFlow implementation](https://github.com/XuyangBai/D3Feat/blob/master/demo_registration.py). But as @qsisi said, since I use KPConv as the backbone, I need to pre-compute neighborhood_limits, the neighborhood indices, etc in collaten_fn, which is quite cumbersome so I still haven't written demo code for PyTorch. I can find time to write the code snippet for pytorch if you really need it.

**Comment by fabiopoiesi** [comment]
Hi,
I actually managed to use the tensorflow implementation successfully.
Thanks for your help.

**Comment by XuyangBai** [comment]
Glad to here that:)

**Comment by houyongkuo** [comment]
> Hi,
> 
> Do you guys have a simple demo code, that given two point clouds, D3Feat computes the features and then these features are used to register the two point clouds with RANSAC?
> 
> Thanks

Hi, I have finished a demo about 3dmatch dataset for PyTorch. 
[demo](https://github.com/HOUYONGKUO/D3Feat.pytorch/blob/master/demo.py)

**Comment by zouyajing** [comment]
> > Hi,
> > Do you guys have a simple demo code, that given two point clouds, D3Feat computes the features and then these features are used to register the two point clouds with RANSAC?
> > Thanks
> 
> Hi, I have finished a demo about 3dmatch dataset for PyTorch. [demo](https://github.com/HOUYONGKUO/D3Feat.pytorch/blob/master/demo.py)

thx a lot. do you have the D3Feat pytorch model backup? seem the google drive expire and the author is not taking care any more.
