### ISSUE TITLE
About test.py

### ISSUE THREAD

**Issue by houyongkuo** [XuyangBai/D3Feat.pytorch#17]
Hello, I recently used test.py to test the results, but I found that there is no *.npy file for the generated descriptors and scores. How to generate or restore it? In addition, the keypoints file provided by 3dmatch is in *.txt format. Can you use it directly? thanks
```
def get_desc(descpath, filename, desc_name):
    desc = np.load(os.path.join(descpath, filename + f'.{desc_name}.npy'))
    return desc
def get_scores(descpath, filename, desc_name):
    scores = np.load(os.path.join(descpath, filename + '.npy'))
    return scores
```

**Comment by qsisi** [comment]
https://github.com/XuyangBai/D3Feat.pytorch/blob/44508b04281d3a728e2da68b2d637249675d1931/test.py#L191

**Comment by houyongkuo** [comment]
> https://github.com/XuyangBai/D3Feat.pytorch/blob/44508b04281d3a728e2da68b2d637249675d1931/test.py#L191

Thank you very much
