### ISSUE TITLE
Torch vision is different 

### ISSUE THREAD

**Issue by wangwen-whu** [XuyangBai/D3Feat.pytorch#2]
Hi Xuyang:
  I have run your code which used pytorch,but it has this bug
![image](https://user-images.githubusercontent.com/71618211/93728905-afe78880-fbf4-11ea-91b7-14dd3572df06.png)
  I found this error and other errors were caused by the version of Pytorch, vision 1.4 and above has this torch.logical_not() attribute.
  So could you update a new right environment.yml? Or tell me the right vision of pytorch and cuda and cudnn?

**Comment by XuyangBai** [comment]
Hi @wangwen-whu Thanks for your interest. I have updated the environment.yml. 

Best,
Xuyang
