### ISSUE TITLE
train and test the network

### ISSUE THREAD

**Issue by david-ngo-sixense** [XuyangBai/D3Feat.pytorch#3]
Thanks for your work. It is very interesting.
Can you explain how to test the network? I run:
python test.py
and the error: FileNotFoundError: [Errno 2] No such file or directory: '/data/D3Feat/snapshot//config.json'

And how did you train the network ? It sounds that the file train.py is missing.
Thanks.

**Comment by XuyangBai** [comment]
`training_3DMatch.py` is for training 

For testing:
python test.py --chosen_snapshot [timestr of the model]

**Comment by david-ngo-sixense** [comment]
Thanks for your quick reply. I have this error when training:
Traceback (most recent call last):
  File "training_3DMatch.py", line 128, in <module>
    dist_type=config.dist_type,
AttributeError: 'EasyDict' object has no attribute 'dist_type'

You did not define the argument for 'dis_type' in config.py.

I do not understand the testing. For example, when I run:
python test.py --chosen_snapshot 15
I have the error: 
FileNotFoundError: [Errno 2] No such file or directory: '/data/D3Feat/snapshot/15/config.json'
The file config.json is created after training ?
I download the dataset 3DMatch following your tensorflow respository. And there is no config.json file.

**Comment by XuyangBai** [comment]
After you train the model, there will be a folder in `snapshot` and the folder name is what you used for testing. The config.json is also generated automatically in this folder
```
python test.py --chosen_snapshot [the foldername]
```
