### ISSUE TITLE
AttributeError: 'EasyDict' object has no attribute 'dist_type

### ISSUE THREAD

**Issue by houyongkuo** [XuyangBai/D3Feat.pytorch#4]
Thanks for your work. It is very interesting.
Can you explain how to test the network? I run:
training_3DMatch.py
and the error: AttributeError: 'EasyDict' object has no attribute 'dist_type'

Dist_type is indeed missing in the config.py file

Thanks.

**Comment by XuyangBai** [comment]
I forgot to update the config when adding circle loss support. You may add the following code to the config.py by yourself first
```
loss_arg.add_argument('--dist_type', type=str, default='euclidean')
```

I will update the config.py later, sorry for the incovience.

**Comment by houyongkuo** [comment]
Thanks!  I do not why I got the accuracy of the result is only 63.84375 after training. When I run 'python test.py --chosen_snapshot D3Feat04161954
', I got the error:
No such file or directory: 'geometric_registration/D3Feat04161954/keypoints/sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika/cloud_bin_0.npy',
I confirmed that 'geometric_registration/D3Feat04161954/' is indeed an empty folder.
I am confused what causes this issue.

**Comment by XuyangBai** [comment]
The accuracy is only the intermediate results which I output to monitor the training process, and 63.8% is normal. It represents the percentage of `d_pos < d_neg` for the pairs of descriptors used in loss computation and not the same with Registration recall. For testing, you have to generate the descriptor first, there are some parameters in `test.py` as shown below

https://github.com/XuyangBai/D3Feat.pytorch/blob/40203d748b6b5c28edf1c3422c0f2ae1023346b1/test.py#L132-L138

So you should use 

```
python test.py --chosen_snapshot D3Feat04161954 --genereate_features
```

**Comment by houyongkuo** [comment]
Thanks!
I have completed the training process, but I don’t know how to test my point cloud data to complete the registration.

**Comment by XuyangBai** [comment]
After completing the training process, you can extract the descriptor using the trained model, you can use RANSAC to get the transformation between two point clouds. You may see the demo [here](https://github.com/XuyangBai/D3Feat/blob/master/demo_registration.py), the function `execute_global_registration` get the point cloud, per point features as input and produce an registration result as output
