### ISSUE TITLE
 Could you provide the test code on the ETH dataset

### ISSUE THREAD

**Issue by aosheng1996** [XuyangBai/D3Feat.pytorch#6]
Hello Xuyang,

Thank you for your great works and I have benefited a lot.

I have a small request, could you provide the test code on the ETH dataset? I tried to write the test code on the ETH dataset, and changed the configuration of the `test_ETH` with `voxel_grid = 0.0625` and `first_subsampling_dl = 0.0625/0.11`. I used the PyTorch pretrained model you provided (https://github.com/XuyangBai/D3Feat/issues/30). During debugging, the values of `conv_radius` and `kernel_points` have changed, but the test code I wrote always gets a 0% FMR. I don't know where the problem is, I really hope to get your help. 

Looking forward to your reply. Thank you very much.

Best,
Sheng

**Comment by XuyangBai** [comment]
Hi Sheng.

Thanks for your interest. So you mean you need an evaluating script for ETH in PyTorch? We already have a script for evaluating ETH in TensorFlow.

**Comment by aosheng1996** [comment]
Hi Xuyang,

Thank you for your reply. 

Sorry to trouble you,  I really want an evaluating script for ETH in PyTorch. Would it be convenient for you to take time to provide it?

Best,
Sheng

**Comment by XuyangBai** [comment]
Sure, I will write an evaluation script after I get some time.

**Comment by aosheng1996** [comment]
Hi Xuyang,

Thank you for your generosity and look forward to your updates. 

Best,
Sheng
