### ISSUE TITLE
Trained Model On 3D Match Dataset for PyTorch

### ISSUE THREAD

**Issue by yuvalH9** [XuyangBai/D3Feat.pytorch#8]
Hi,
First of all thanks for providing the PyTorch version of your project.

Can you also supply the trained model, as you did on Tensorflow version, for the 3Dmatch dataset?

Regards
Yuval

**Comment by XuyangBai** [comment]
Hi, you can download the PyTorch pretrained model here https://drive.google.com/file/d/1aE_Fkt9Cw3Dgq8MbgW5CGCxhy9f5P_Yu/view?usp=sharing but the detector performance is slightly worse than the TF version (the descriptor is better). Sorry I currently have no time to dig into the reason.

Best,
Xuyang.

**Comment by yuvalH9** [comment]
Thanks, I will try it out.
I also encountered another issue of missing keypoints `.npy` files when running the test file on `get_keypts` function.

How can I get\ generate those files?

Yuval

**Comment by XuyangBai** [comment]
When you use `test.py` you can set the flag `--generate_features` to generate the descriptor and detection score first.

**Comment by yuvalH9** [comment]
Thanks for that!

I also got the following error when I try to load your trained model:

`RuntimeError: Error(s) in loading state_dict for KPFCNN:
	Missing key(s) in state_dict: "encoder_blocks.1.unary1.mlp.bias", "encoder_blocks.1.unary2.mlp.bias", "encoder_blocks.1.unary_shortcut.mlp.bias", "encoder_blocks.2.unary1.mlp.bias", "encoder_blocks.2.unary2.mlp.bias", "encoder_blocks.3.unary1.mlp.bias", "encoder_blocks.3.unary2.mlp.bias", "encoder_blocks.3.unary_shortcut.mlp.bias", "encoder_blocks.4.unary1.mlp.bias", "encoder_blocks.4.unary2.mlp.bias", "encoder_blocks.5.unary1.mlp.bias", "encoder_blocks.5.unary2.mlp.bias", "encoder_blocks.6.unary1.mlp.bias", "encoder_blocks.6.unary2.mlp.bias", "encoder_blocks.6.unary_shortcut.mlp.bias", "encoder_blocks.7.unary1.mlp.bias", "encoder_blocks.7.unary2.mlp.bias", "encoder_blocks.8.unary1.mlp.bias", "encoder_blocks.8.unary2.mlp.bias", "encoder_blocks.9.unary1.mlp.bias", "encoder_blocks.9.unary2.mlp.bias", "encoder_blocks.9.unary_shortcut.mlp.bias", "encoder_blocks.10.unary1.mlp.bias", "encoder_blocks.10.unary2.mlp.bias", "encoder_blocks.11.unary1.mlp.bias", "encoder_blocks.11.unary2.mlp.bias", "encoder_blocks.12.unary1.mlp.bias", "encoder_blocks.12.unary2.mlp.bias", "encoder_blocks.12.unary_shortcut.mlp.bias", "encoder_blocks.13.unary1.mlp.bias", "encoder_blocks.13.unary2.mlp.bias", "decoder_blocks.1.mlp.bias", "decoder_blocks.3.mlp.bias", "decoder_blocks.5.mlp.bias", "decoder_blocks.7.mlp.bias".
`

I did not change the model, I used the given one in `test.py` file.

Is it possible that for that given pretrained model you used other architecture?

Yuval

**Comment by XuyangBai** [comment]
Hi,  that is because I have changed the code in `block.py` after the release the pre-trained model

https://github.com/XuyangBai/D3Feat.pytorch/blob/cb44a16657cf2da3e5167c539555c9bd90df2da8/models/blocks.py#L498
and 
https://github.com/XuyangBai/D3Feat.pytorch/blob/cb44a16657cf2da3e5167c539555c9bd90df2da8/models/blocks.py#L532

You can set the `bias=False` to load the released model. The bias term doesn't give much influence on final performance.
